### PR TITLE
Update list of CT logs

### PR DESCRIPTION
**Pull request by acohn**
I've added every publicly-known log that is currently responsive and issuing STHs. Some of these (e.g. the IPv6-only Behind The Sofa) may not be useful additions to the Honeybee; let me know and I'd be happy to yank them out.

I have removed Google's Aviator, Venafi's Gen1, and PuChuangSiDa's certificate-transparency.cn logs, as they are frozen or defunct.

I have not included the Google Xenon logs, as their public keys are not (yet?) known outside Google and therefore it's not possible to verify any STH they sign.

### CODE REVIEW

**Comment by AGWA** [comment]
Thank you, @acohn!

A few things:

1. Aviator should still be monitored, since it's fully trusted by Chrome.  Although it's not _supposed_ to produce any more STHs, the point of ct-honeybee is to catch logs doing things they aren't supposed to do.

2. Please add back the auditor URLs to the permissions list in manifest.json.

3. My inclination is to only monitor logs that are trusted by user agents or are applying to be trusted by user agents, since those are the only logs which have committed to act in the public interest and which can be sanctioned should an inconsistent STH be discovered.   The Python version of ct-honeybee has an up-to-date list of such logs: https://github.com/SSLMate/ct-honeybee/blob/master/ct-honeybee#L40-L78  But maybe it's useful to monitor other logs as well; do you have any thoughts?

**Comment by acohn** [comment]
Thanks for the review!
1. Hadn't considered that - a very good point. Added Aviator back. Also, would it make sense to add Cloudflare's Nimbus 2017 log for the same reason?
2. Nice catch. Admittedly, my testing went as far as "does it successfully fetch STHs and queue them to be sent to the monitor", but not as far as "are the STHs showing up at the monitor." Oops!
3. My inclination is to monitor any log that either your or Graham Edgecombe's monitors care about. Regardless of the possibility of formal sanctions, it is still valuable to know if a log starts misbehaving. For example, I have been logging expired certificates to Google's Daedalus over the past couple days and I would certainly like to know if it starts misbehaving so I can redirect my efforts elsewhere.

**Comment by AGWA** [comment]
Those are good arguments for monitoring all logs.  I've merged this PR, and added Nimbus 2017 in 061ea7ab3c254580dc41b359ba5a7fff1cf47669.  Thanks again!

**Comment by AGWA** [comment]
I've uploaded version 0.0.4 to the Chrome Web Store.

**Pull request merged**
